### ISSUE TITLE
わからないこと

### ISSUE THREAD

**Issue by shimami1024** [shimami1024/Original#3]
画像をimageViewとマッチさせる（大きさを同じにする）
backgroundをユーザーが自由に設定できるようにする
画像を傾ける方法
drawableに取り込んだ画像の大きさを変える方法

あとimageViewって.jpgとか.psdいけるんですか？
（加工した画像を取り込むことを考えると大切なので）

**Comment by y-ogawara** [comment]
@shimami1024 
・画像をimageViewとマッチさせる（大きさを同じにする）
　　　　・fitXYとかで出来るけど、縦横比がめちゃくちゃになるよ！

・backgroundをユーザーが自由に設定できるようにする
　　　　・自分で実装してなかった？

・画像を傾ける方法
　　　　・ここを参考にして！
　　　　https://github.com/y-ogawara/mikiTest/blob/master/app/src/main/java/com/example/y_ogawara/mikitest/MainActivity.java

・drawableに取り込んだ画像の大きさを変える方法
　　　　・もうちょっと具体的にほしい！

・あとimageViewって.jpgとか.psdいけるんですか？
　　　　・PSDは無理だけど、jpegは一応できる！
　　　　　PNGは透過画像使えるから、それで良いんじゃ？

**Comment by shimami1024** [comment]
すいません
木曜日まで修学旅行なのでissue書けません

**Comment by shimami1024** [comment]
genymotionのギャラリーに画像入れるのってどうやるんですか？
